# Dependabot configuration file

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    registries: "*"
    groups:
      # Group kotlin, ksp and compose compiler updates
      kotlin:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlin.*"
          - "com.google.devtools.ksp"
          - "androidx.compose.compiler:compiler"
      # Group remaining updates
      updates:
        patterns: ["*"]

  # Check for updates to GitHub Actions every week
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

# Add Google maven repository as registry
registries:
  maven-google:
    type: "maven-repository"
    url: "https://maven.google.com"
